from sqlalchemy import Enum

NATIONALITIES: tuple[str, ...] = (
    "American",
    "Argentinian",
    "Australian",
    "Austrian",
    "Belgian",
    "Beninois",
    "Brazilian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Columbian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Dutch",
    "Egyptian",
    "English",
    "Finnish",
    "French",
    "German",
    "Ghanaian",
    "Greek",
    "Guatemalan",
    "Guyanese",
    "Hungarian",
    "Icelandic",
    "Indian",
    "Indonesian",
    "Irish",
    "Israeli",
    "Italian",
    "Jamaican",
    "Japanese",
    "Kenyan",
    "Korean",
    "Latvian",
    "Liberian",
    "Lithuanian",
    "Luxembourgish",
    "Malaysian",
    "Malian",
    "Mexican",
    "New Zealander",
    "Nigerian",
    "Northern Irish",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Saudi",
    "Scottish",
    "Serbian",
    "Singaporean",
    "Somalian",
    "South African",
    "Spanish",
    "Swazi",
    "Swedish",
    "Swiss",
    "Taiwanese",
    "Thai",
    "Ukrainian",
    "Unknown",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
)

nationality = Enum(*NATIONALITIES, name="nationality", native_enum=True)
